In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("../data/raw/cardekho.csv")

In [4]:
df.head(10)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage(km/ltr/kg),engine,max_power,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78,5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.2,5.0
5,Hyundai Xcent 1.2 VTVT E Plus,2017,440000,45000,Petrol,Individual,Manual,First Owner,20.14,1197.0,81.86,5.0
6,Maruti Wagon R LXI DUO BSIII,2007,96000,175000,LPG,Individual,Manual,First Owner,17.30,1061.0,57.5,5.0
7,Maruti 800 DX BSII,2001,45000,5000,Petrol,Individual,Manual,Second Owner,16.10,796.0,37,4.0
8,Toyota Etios VXD,2011,350000,90000,Diesel,Individual,Manual,First Owner,23.59,1364.0,67.1,5.0
9,Ford Figo Diesel Celebration Edition,2013,200000,169000,Diesel,Individual,Manual,First Owner,20.00,1399.0,68.1,5.0

In [8]:
df.duplicated().sum()

np.int64(1202)

In [9]:
df = df.drop_duplicates()

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
# renaming mileage 
df = df.rename(columns={"mileage(km/ltr/kg)": "mileage"})

In [12]:
df.sample(3)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
3943,Maruti Swift Dzire VXI,2014,480000,72000,Petrol,Individual,Manual,First Owner,19.10,1197.0,85.8,5.0
232,Maruti Wagon R LXI Optional,2016,350000,140000,Petrol,Individual,Manual,First Owner,20.51,998.0,67.04,5.0
5593,Chevrolet Enjoy TCDi LT 7 Seater,2013,355000,136000,Diesel,Individual,Manual,Second Owner,18.20,1248.0,73.8,7.0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6926 entries, 0 to 8125
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6926 non-null   object
 1   year           6926 non-null   int64
 2   selling_price  6926 non-null   int64
 3   km_driven      6926 non-null   int64
 4   fuel           6926 non-null   object
 5   seller_type    6926 non-null   object
 6   transmission   6926 non-null   object
 7   owner          6926 non-null   object
 8   mileage        6718 non-null   float64
 9   engine         6718 non-null   float64
 10  max_power      6721 non-null   object
 11  seats          6718 non-null   float64
dtypes: float64(3), int64(3), object(6)
memory usage: 703.4+ KB

In [14]:
# max_power fromonject to float64
df["max_power"] = pd.to_numeric(df["max_power"], errors="coerce")

In [15]:
df["max_power"].dtype

dtype('float64')

In [16]:
df["brand"] = df["name"].str.strip().str.split().str[0]

In [17]:
df.sample(3)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats,brand
375,Toyota Camry 2.5 Hybrid,2016,2000000,68089,Petrol,Trustmark Dealer,Automatic,First Owner,19.16,2494.0,157.7,5.0,Toyota
1815,Mahindra Jeep MM 540,1995,160000,90000,Diesel,Individual,Manual,Third Owner,NaN,NaN,NaN,NaN,Mahindra
3940,Chevrolet Spark 1.0 LT,2016,160000,50000,Petrol,Individual,Manual,Second Owner,16.20,995.0,62.1,5.0,Chevrolet

In [18]:
df = df.drop(columns=["name"])

In [19]:
df.sample(3)

,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats,brand
8121,2013,260000,50000,Petrol,Individual,Manual,Second Owner,18.90,998.0,67.1,5.0,Maruti
6932,2007,55000,75958,Diesel,Individual,Manual,Second Owner,17.88,1396.0,52.8,5.0,Tata
5579,2008,585000,120000,Diesel,Individual,Automatic,First Owner,14.30,1968.0,140.0,5.0,Volkswagen

In [22]:
# i wanna create car age for the dataset
from datetime import datetime
current_year = datetime.now().year

df["car_age"] = current_year - df["year"]
df = df.drop(columns=["year"])

In [23]:
df.sample(3)

,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats,brand,car_age
601,555000,20000,Petrol,Individual,Manual,Second Owner,15.8,1499.0,110.0,5.0,Ford,11
3055,190000,80000,Petrol,Individual,Manual,Second Owner,16.8,796.0,34.2,8.0,Maruti,10
5184,150000,90000,Petrol,Individual,Manual,Third Owner,13.4,1794.0,125.0,5.0,Toyota,20

In [27]:
miss = (df.isna().sum()/df.shape[0])*100
miss[miss>0]

mileage      3.003176
engine       3.003176
max_power    2.974300
seats        3.003176
dtype: float64

In [28]:
df.to_csv('../data/processed/car_sales_cleaned.csv', index=False)